name: flash_chat
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  animated_text_kit: ^4.2.2
  cloud_firestore: ^4.14.0
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  blurry_modal_progress_hud: ^1.1.1
  flutter_spinkit: ^5.2.0
  shared_preferences: ^2.2.2
  curved_labeled_navigation_bar: ^2.0.2
  rflutter_alert: ^2.0.7
  email_validator: ^2.1.17

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
  - images/
